# Generated by Django 5.1 on 2024-08-30 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rotinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_rotina', models.CharField(max_length=6)),
                ('Nome_rotina', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='rotina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.rotinas'),
            preserve_default=False,
        ),
    ]
