# Generated by Django 5.1 on 2024-08-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_erro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Tipo_erro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.tipo_erro'),
            preserve_default=False,
        ),
    ]
